version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "chore"

  - package-ecosystem: "npm"
    directory: "/extensions"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "chore"
    open-pull-requests-limit: 10
